// <auto-generated />
using System;
using Heliotracker;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Heliotracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260618175629_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Heliotracker.Entities.Grid", b =>
                {
                    b.Property<int>("GridId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GridId"));

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.HasKey("GridId");

                    b.HasIndex("SiteId");

                    b.ToTable("Grids");
                });

            modelBuilder.Entity("Heliotracker.Entities.Panel", b =>
                {
                    b.Property<int>("PanelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PanelId"));

                    b.Property<int>("GridId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastMaintenence")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PeakCapacityKw")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("PanelId");

                    b.HasIndex("GridId");

                    b.ToTable("Panels");
                });

            modelBuilder.Entity("Heliotracker.Entities.PerformanceLog", b =>
                {
                    b.Property<int>("PerformanceLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PerformanceLogId"));

                    b.Property<bool>("Concerned")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("EnergyGeneratedKw")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("PanelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PerformanceLogId");

                    b.HasIndex("PanelId");

                    b.ToTable("PerformanceLogs");
                });

            modelBuilder.Entity("Heliotracker.Entities.Site", b =>
                {
                    b.Property<int>("SiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SiteId"));

                    b.Property<decimal>("SiteLatitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("SiteLongitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("SiteName")
                        .HasColumnType("longtext");

                    b.HasKey("SiteId");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("Heliotracker.Entities.Grid", b =>
                {
                    b.HasOne("Heliotracker.Entities.Site", "Site")
                        .WithMany("Grids")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Heliotracker.Entities.Panel", b =>
                {
                    b.HasOne("Heliotracker.Entities.Grid", "Grid")
                        .WithMany("Panels")
                        .HasForeignKey("GridId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grid");
                });

            modelBuilder.Entity("Heliotracker.Entities.PerformanceLog", b =>
                {
                    b.HasOne("Heliotracker.Entities.Panel", "Panel")
                        .WithMany("PerformanceLogs")
                        .HasForeignKey("PanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Panel");
                });

            modelBuilder.Entity("Heliotracker.Entities.Grid", b =>
                {
                    b.Navigation("Panels");
                });

            modelBuilder.Entity("Heliotracker.Entities.Panel", b =>
                {
                    b.Navigation("PerformanceLogs");
                });

            modelBuilder.Entity("Heliotracker.Entities.Site", b =>
                {
                    b.Navigation("Grids");
                });
#pragma warning restore 612, 618
        }
    }
}
